"""Add Phase 3F context fields

Revision ID: 0b67d5854971
Revises: 836bd63d1299
Create Date: 2026-08-17 19:59:15.237419+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b67d5854971'
down_revision: Union[str, None] = '836bd63d1299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_name', sa.String(length=255), nullable=True, comment='Name of the enclosing class or struct, if any'))
        batch_op.add_column(sa.Column('parent_symbol', sa.String(length=255), nullable=True, comment='Name of the immediate parent symbol, if any'))
        batch_op.add_column(sa.Column('module_name', sa.String(length=255), nullable=True, comment='Derived module/package name based on file path'))
        batch_op.add_column(sa.Column('context_path', sa.String(length=512), nullable=True, comment='Deterministic dot-separated path (e.g. ClassName.method_name)'))

    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index_version', sa.Integer(), server_default='1', nullable=False, comment='Schema version for vector and BM25 indices'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_column('index_version')

    with op.batch_alter_table('code_chunks', schema=None) as batch_op:
        batch_op.drop_column('context_path')
        batch_op.drop_column('module_name')
        batch_op.drop_column('parent_symbol')
        batch_op.drop_column('class_name')

    # ### end Alembic commands ###
