"""phase3b_indexed_file

Revision ID: f6dabb48c201
Revises: 6a3a3a9807a8
Create Date: 2026-08-09 21:44:45.128410+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6dabb48c201'
down_revision: Union[str, None] = '6a3a3a9807a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexed_files',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('ingestion_id', sa.UUID(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False, comment='Path relative to the repository root'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='Size of the file in bytes'),
    sa.Column('extension', sa.String(length=255), nullable=False, comment="File extension, including the dot (e.g., '.py'). Empty string if no extension."),
    sa.Column('is_binary', sa.Boolean(), nullable=False, comment='True if detected as a binary file'),
    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of the file content'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key — UUID v4 generated at insert time'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['ingestion_id'], ['repository_ingestions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indexed_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indexed_files_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_indexed_files_ingestion_id'), ['ingestion_id'], unique=False)
        batch_op.create_index('ix_indexed_files_ingestion_path_unique', ['ingestion_id', 'relative_path'], unique=True)
        batch_op.create_index(batch_op.f('ix_indexed_files_relative_path'), ['relative_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_indexed_files_repository_id'), ['repository_id'], unique=False)

    with op.batch_alter_table('repository_ingestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress_message', sa.String(length=255), nullable=True, comment='Current progress message of the ingestion'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository_ingestions', schema=None) as batch_op:
        batch_op.drop_column('progress_message')

    with op.batch_alter_table('indexed_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indexed_files_repository_id'))
        batch_op.drop_index(batch_op.f('ix_indexed_files_relative_path'))
        batch_op.drop_index('ix_indexed_files_ingestion_path_unique')
        batch_op.drop_index(batch_op.f('ix_indexed_files_ingestion_id'))
        batch_op.drop_index(batch_op.f('ix_indexed_files_id'))

    op.drop_table('indexed_files')
    # ### end Alembic commands ###
