"""phase3c_code_symbols

Revision ID: bf8b6381b084
Revises: f6dabb48c201
Create Date: 2026-08-10 07:07:24.637613+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8b6381b084'
down_revision: Union[str, None] = 'f6dabb48c201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_symbols',
    sa.Column('indexed_file_id', sa.UUID(), nullable=False),
    sa.Column('parent_symbol_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('symbol_type', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('start_column', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('end_column', sa.Integer(), nullable=False),
    sa.Column('start_byte', sa.Integer(), nullable=True),
    sa.Column('end_byte', sa.Integer(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True, comment='Extracted signature (e.g. def func(args) -> Ret)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key — UUID v4 generated at insert time'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['indexed_file_id'], ['indexed_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_symbol_id'], ['code_symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_symbols', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_symbols_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_symbols_indexed_file_id'), ['indexed_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_symbols_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_symbols_parent_symbol_id'), ['parent_symbol_id'], unique=False)

    with op.batch_alter_table('repository_ingestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('parsed_file_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('symbol_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('unsupported_file_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('parse_error_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository_ingestions', schema=None) as batch_op:
        batch_op.drop_column('parse_error_count')
        batch_op.drop_column('unsupported_file_count')
        batch_op.drop_column('symbol_count')
        batch_op.drop_column('parsed_file_count')
        batch_op.drop_column('file_count')

    with op.batch_alter_table('code_symbols', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_symbols_parent_symbol_id'))
        batch_op.drop_index(batch_op.f('ix_code_symbols_name'))
        batch_op.drop_index(batch_op.f('ix_code_symbols_indexed_file_id'))
        batch_op.drop_index(batch_op.f('ix_code_symbols_id'))

    op.drop_table('code_symbols')
    # ### end Alembic commands ###
