"""initial_schema_with_github

Revision ID: e37a19280ef8
Revises:
Create Date: 2026-08-09 08:02:20.090762+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e37a19280ef8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Display name of the organization",
        ),
        sa.Column(
            "slug",
            sa.String(length=255),
            nullable=False,
            comment="URL-safe identifier (e.g., 'acme-corp')",
        ),
        sa.Column(
            "description",
            sa.String(length=1000),
            nullable=True,
            comment="Optional description of the organization",
        ),
        sa.Column(
            "avatar_url",
            sa.String(length=2048),
            nullable=True,
            comment="Organization profile picture URL",
        ),
        sa.Column(
            "github_org_id",
            sa.Integer(),
            nullable=True,
            comment="GitHub organization ID for webhook routing",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Primary key — UUID v4 generated at insert time",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when the record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when the record was last updated (UTC)",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organizations_github_org_id"), "organizations", ["github_org_id"], unique=True
    )
    op.create_index(op.f("ix_organizations_id"), "organizations", ["id"], unique=False)
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column(
            "email",
            sa.String(length=320),
            nullable=False,
            comment="User's email address — must be unique",
        ),
        sa.Column("full_name", sa.String(length=255), nullable=True, comment="User's display name"),
        sa.Column(
            "avatar_url",
            sa.String(length=2048),
            nullable=True,
            comment="URL to the user's profile picture",
        ),
        sa.Column(
            "hashed_password",
            sa.String(length=255),
            nullable=True,
            comment="bcrypt hash — null for OAuth-only accounts",
        ),
        sa.Column(
            "github_id",
            sa.Integer(),
            nullable=True,
            comment="GitHub user ID for OAuth account linking",
        ),
        sa.Column(
            "github_username",
            sa.String(length=255),
            nullable=True,
            comment="GitHub username (login)",
        ),
        sa.Column(
            "github_access_token",
            sa.String(length=2048),
            nullable=True,
            comment="Encrypted GitHub access token for Phase 2 API access",
        ),
        sa.Column(
            "last_login_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of the last successful login",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="False = soft-deleted or suspended account",
        ),
        sa.Column(
            "is_email_verified",
            sa.Boolean(),
            nullable=False,
            comment="True once the user verifies their email address",
        ),
        sa.Column(
            "is_superuser",
            sa.Boolean(),
            nullable=False,
            comment="True for internal admin accounts only",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Primary key — UUID v4 generated at insert time",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when the record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when the record was last updated (UTC)",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_github_id"), "users", ["github_id"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "api_keys",
        sa.Column("user_id", sa.UUID(), nullable=False, comment="User who owns this API key"),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Human-readable name for the key (e.g., 'CI Pipeline')",
        ),
        sa.Column(
            "key_prefix",
            sa.String(length=8),
            nullable=False,
            comment="First 8 characters of the raw key — shown in UI for identification",
        ),
        sa.Column(
            "key_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 hash of the raw key — used for lookup and validation",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="Key lifecycle: active | revoked | expired",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Optional expiry — null means the key never expires",
        ),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of the last API request authenticated with this key",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Primary key — UUID v4 generated at insert time",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when the record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when the record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_id"), "api_keys", ["id"], unique=False)
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_index(op.f("ix_api_keys_status"), "api_keys", ["status"], unique=False)
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Immutable event timestamp (UTC)",
        ),
        sa.Column(
            "actor_id",
            sa.UUID(),
            nullable=True,
            comment="User who performed the action (null for system actions)",
        ),
        sa.Column(
            "action",
            sa.String(length=100),
            nullable=False,
            comment="Action identifier (e.g., 'repo.connected', 'auth.login.failed')",
        ),
        sa.Column(
            "resource_type",
            sa.String(length=100),
            nullable=True,
            comment="Type of the affected resource (e.g., 'repository', 'user')",
        ),
        sa.Column(
            "resource_id",
            sa.String(length=36),
            nullable=True,
            comment="ID of the affected resource",
        ),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=True,
            comment="Client IP address at the time of the action",
        ),
        sa.Column(
            "user_agent", sa.String(length=512), nullable=True, comment="Client User-Agent header"
        ),
        sa.Column(
            "metadata_json",
            sa.Text(),
            nullable=True,
            comment="JSON-encoded additional context for the audit event",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Primary key — UUID v4 generated at insert time",
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(op.f("ix_audit_logs_resource_id"), "audit_logs", ["resource_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), nullable=False, comment="Recipient user"),
        sa.Column(
            "notification_type",
            sa.String(length=100),
            nullable=False,
            comment="Event type (e.g., 'analysis_complete', 'member_invited')",
        ),
        sa.Column(
            "title",
            sa.String(length=255),
            nullable=False,
            comment="Short human-readable notification title",
        ),
        sa.Column(
            "body", sa.Text(), nullable=True, comment="Optional longer notification message body"
        ),
        sa.Column(
            "payload",
            sa.Text(),
            nullable=True,
            comment="JSON-encoded structured data for the notification",
        ),
        sa.Column("is_read", sa.Boolean(), nullable=False, comment="False = unread notification"),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Primary key — UUID v4 generated at insert time",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when the record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when the record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.create_index(op.f("ix_notifications_is_read"), "notifications", ["is_read"], unique=False)
    op.create_index(
        op.f("ix_notifications_notification_type"),
        "notifications",
        ["notification_type"],
        unique=False,
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "organization_memberships",
        sa.Column("organization_id", sa.UUID(), nullable=False, comment="FK to organizations"),
        sa.Column("user_id", sa.UUID(), nullable=False, comment="FK to users"),
        sa.Column(
            "role",
            sa.String(length=50),
            nullable=False,
            comment="Member's role: owner | admin | member | viewer",
        ),
        sa.Column(
            "invited_by_id", sa.UUID(), nullable=True, comment="User who sent the invitation"
        ),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Primary key — UUID v4 generated at insert time",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when the record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when the record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["invited_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "user_id", name="uq_org_user_membership"),
    )
    op.create_index(
        op.f("ix_organization_memberships_id"), "organization_memberships", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_organization_memberships_organization_id"),
        "organization_memberships",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_memberships_user_id"),
        "organization_memberships",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "repositories",
        sa.Column(
            "organization_id",
            sa.UUID(),
            nullable=True,
            comment="Organization that owns this repository (null for personal repos)",
        ),
        sa.Column(
            "owner_id", sa.UUID(), nullable=False, comment="User who connected this repository"
        ),
        sa.Column(
            "github_repo_id",
            sa.Integer(),
            nullable=False,
            comment="GitHub repository ID (stable across renames)",
        ),
        sa.Column(
            "full_name",
            sa.String(length=512),
            nullable=False,
            comment="GitHub full name: 'owner/repo' (e.g., 'acme-corp/api')",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Repository name without owner prefix",
        ),
        sa.Column(
            "description", sa.Text(), nullable=True, comment="Repository description from GitHub"
        ),
        sa.Column(
            "html_url",
            sa.String(length=2048),
            nullable=False,
            comment="GitHub web URL for the repository",
        ),
        sa.Column(
            "default_branch",
            sa.String(length=255),
            nullable=False,
            comment="Default branch name (usually 'main' or 'master')",
        ),
        sa.Column(
            "is_private",
            sa.Boolean(),
            nullable=False,
            comment="True if the repository is private on GitHub",
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            comment="Current analysis pipeline status",
        ),
        sa.Column(
            "last_analyzed_at",
            sa.Uuid(),
            nullable=True,
            comment="Timestamp of the last successful analysis completion",
        ),
        sa.Column(
            "analysis_error",
            sa.Text(),
            nullable=True,
            comment="Error message from the last failed analysis attempt",
        ),
        sa.Column(
            "last_commit_sha",
            sa.String(length=40),
            nullable=True,
            comment="SHA of the commit used in the last analysis",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Primary key — UUID v4 generated at insert time",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when the record was created (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Timestamp when the record was last updated (UTC)",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_repositories_full_name"), "repositories", ["full_name"], unique=False)
    op.create_index(
        op.f("ix_repositories_github_repo_id"), "repositories", ["github_repo_id"], unique=True
    )
    op.create_index(op.f("ix_repositories_id"), "repositories", ["id"], unique=False)
    op.create_index(
        op.f("ix_repositories_organization_id"), "repositories", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_repositories_owner_id"), "repositories", ["owner_id"], unique=False)
    op.create_index(op.f("ix_repositories_status"), "repositories", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_repositories_status"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_owner_id"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_organization_id"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_id"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_github_repo_id"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_full_name"), table_name="repositories")
    op.drop_table("repositories")
    op.drop_index(
        op.f("ix_organization_memberships_user_id"), table_name="organization_memberships"
    )
    op.drop_index(
        op.f("ix_organization_memberships_organization_id"), table_name="organization_memberships"
    )
    op.drop_index(op.f("ix_organization_memberships_id"), table_name="organization_memberships")
    op.drop_table("organization_memberships")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_notification_type"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_is_read"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_audit_logs_resource_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_status"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_github_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_id"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_github_org_id"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
