"""phase2_repo

Revision ID: 8ea834cae1b5
Revises: e37a19280ef8
Create Date: 2026-08-09 11:08:14.483857+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8ea834cae1b5'
down_revision: str | None = 'e37a19280ef8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_connected_repositories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'repository_id')
    )
    with op.batch_alter_table('repositories') as batch_op:
        batch_op.drop_index(op.f('ix_repositories_owner_id'))
        # Depending on the backend (postgres vs sqlite), you might need to handle foreign keys conditionally or ignore them.
        # SQLite drop column with batch_op doesn't strictly need drop_constraint.
        # To be safe for both, we ignore errors or just drop the column.
        # If we use render_as_batch=True it will reconstruct the table.
        batch_op.drop_constraint('repositories_owner_id_fkey', type_='foreignkey')
        batch_op.drop_column('owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_connected_repositories')

    with op.batch_alter_table('repositories') as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key('repositories_owner_id_fkey', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(op.f('ix_repositories_owner_id'), ['owner_id'], unique=False)
    # ### end Alembic commands ###
