"""phase3a_ingestion

Revision ID: 6a3a3a9807a8
Revises: 8ea834cae1b5
Create Date: 2026-08-09 21:32:32.809735+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3a3a9807a8'
down_revision: Union[str, None] = '8ea834cae1b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_ingestions',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='Timestamp when the Celery worker actually started the job'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Timestamp when the job finished (success or failure)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Safe error message if the job failed'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key — UUID v4 generated at insert time'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repository_ingestions', schema=None) as batch_op:
        batch_op.create_index('ix_repo_ingestions_active_unique', ['repository_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'running')"))
        batch_op.create_index(batch_op.f('ix_repository_ingestions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repository_ingestions_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repository_ingestions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repository_ingestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repository_ingestions_status'))
        batch_op.drop_index(batch_op.f('ix_repository_ingestions_repository_id'))
        batch_op.drop_index(batch_op.f('ix_repository_ingestions_id'))
        batch_op.drop_index('ix_repo_ingestions_active_unique', postgresql_where=sa.text("status IN ('pending', 'running')"))

    op.drop_table('repository_ingestions')
    # ### end Alembic commands ###
