"""Add CodeChunk model

Revision ID: 836bd63d1299
Revises: 7da64cf76319
Create Date: 2026-08-11 18:29:24.176188+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836bd63d1299'
down_revision: Union[str, None] = '7da64cf76319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_chunks',
    sa.Column('indexed_file_id', sa.UUID(), nullable=False),
    sa.Column('code_symbol_id', sa.UUID(), nullable=True),
    sa.Column('parent_chunk_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False, comment='The actual text content to be embedded'),
    sa.Column('chunk_type', sa.String(length=50), nullable=False, comment="e.g., 'class', 'function', 'file', 'method'"),
    sa.Column('symbol_name', sa.Text(), nullable=True, comment='Name of the semantic symbol, if applicable'),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('start_byte', sa.Integer(), nullable=True),
    sa.Column('end_byte', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of the content to detect unchanged chunks during re-indexing'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key — UUID v4 generated at insert time'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['code_symbol_id'], ['code_symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indexed_file_id'], ['indexed_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['code_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('code_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_code_chunks_code_symbol_id'), ['code_symbol_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_chunks_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_chunks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_chunks_indexed_file_id'), ['indexed_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_code_chunks_parent_chunk_id'), ['parent_chunk_id'], unique=False)

    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('repositories_organization_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('repositories_organization_id_fkey'), 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('code_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_chunks_parent_chunk_id'))
        batch_op.drop_index(batch_op.f('ix_code_chunks_indexed_file_id'))
        batch_op.drop_index(batch_op.f('ix_code_chunks_id'))
        batch_op.drop_index(batch_op.f('ix_code_chunks_content_hash'))
        batch_op.drop_index(batch_op.f('ix_code_chunks_code_symbol_id'))

    op.drop_table('code_chunks')
    # ### end Alembic commands ###
