"""fix_last_analyzed_at_type

Revision ID: 7da64cf76319
Revises: bf8b6381b084
Create Date: 2026-08-10 20:53:52.073622+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da64cf76319'
down_revision: Union[str, None] = 'bf8b6381b084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Cannot auto-cast UUID -> TIMESTAMP; use raw SQL with USING clause.
    # Since all existing values are NULL (the column was never properly populated),
    # we can safely cast NULL::uuid to NULL::timestamp.
    op.execute(
        "ALTER TABLE repositories ALTER COLUMN last_analyzed_at TYPE TIMESTAMP WITHOUT TIME ZONE "
        "USING NULL::TIMESTAMP WITHOUT TIME ZONE"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.alter_column('last_analyzed_at',
               existing_type=sa.DateTime(),
               type_=sa.UUID(),
               existing_comment='Timestamp of the last successful analysis completion',
               existing_nullable=True)

    # ### end Alembic commands ###
