"""
app/modules/retrieval/reranker.py

Defines the retrieval reranker provider abstraction and a deterministic mock implementation.
"""

from abc import ABC, abstractmethod
from typing import List

from app.core.logging import get_logger
from app.modules.retrieval.schemas import RerankerCandidate

logger = get_logger(__name__)


class RerankerProvider(ABC):
    """
    Abstract base class for all reranker providers.
    """

    @abstractmethod
    async def rerank(
        self, query: str, candidates: list[RerankerCandidate], top_k: int
    ) -> list[RerankerCandidate]:
        """
        Rerank the candidates based on the query.

        Args:
            query: The user search query.
            candidates: The candidate pool generated by RRF.
            top_k: The final number of results to return.

        Returns:
            A new list of RerankerCandidate, ordered by the provider's score,
            truncated to top_k. The returned candidates MUST preserve
            the original metadata (rrf_score, semantic_rank, keyword_rank)
            and populate `reranker_score`.
        """
        pass


class MockRerankerProvider(RerankerProvider):
    """
    This provider is a test provider and is not intended to represent production reranking quality.

    It performs deterministic lexical overlap scoring on Phase 3F context fields to
    verify pipeline correctness without external dependencies.
    """

    async def rerank(
        self, query: str, candidates: list[RerankerCandidate], top_k: int
    ) -> list[RerankerCandidate]:
        query_terms = set(query.lower().split())
        if not query_terms:
            # If empty query, just preserve order and assign generic scores
            for i, c in enumerate(candidates):
                c.reranker_score = 1.0 / (i + 1)
            return candidates[:top_k]

        scored_candidates = []
        for candidate in candidates:
            score = 0.0

            # Deterministic weighted lexical matching
            if candidate.context_path:
                context_terms = set(candidate.context_path.lower().replace(".", " ").split())
                if query_terms & context_terms:
                    score += 5.0 * len(query_terms & context_terms)
            
            if candidate.symbol_name:
                symbol_terms = set(candidate.symbol_name.lower().split("_"))
                if query_terms & symbol_terms:
                    score += 4.0 * len(query_terms & symbol_terms)
            
            if candidate.class_name:
                class_terms = set(candidate.class_name.lower().split()) # Not perfectly camelCase split but works for exact overlap
                if query_terms & class_terms:
                    score += 3.0 * len(query_terms & class_terms)
            
            # Simple term presence in content
            content_lower = candidate.content.lower()
            term_matches = sum(1 for term in query_terms if term in content_lower)
            score += 1.0 * term_matches

            # Tie breaker: fallback to existing rrf_score to maintain determinism
            tie_breaker = candidate.rrf_score if candidate.rrf_score is not None else 0.0

            candidate.reranker_score = score + (tie_breaker * 0.001)
            scored_candidates.append(candidate)

        # Sort by reranker_score descending
        scored_candidates.sort(key=lambda c: c.reranker_score or 0.0, reverse=True)

        return scored_candidates[:top_k]
